import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import publicDigitalDiagnosisRouter from "./public-digital-diagnosis";
import publicFoundersRouter from "./public-founders";
import publicProposalsRouter from "./public-proposals";
import publicInvoicesRouter from "./public-invoices";
import publicCatalogRouter from "./public-catalog";
import clientsRouter from "./clients";
import clientAccessRouter from "./client-access";
import clientBrandRouter from "./client-brand";
import clientOnboardingRouter from "./client-onboarding";
import clientTimelineRouter from "./client-timeline";
import clientNotesRouter from "./client-notes";
import projectsRouter from "./projects";
import agentsRouter from "./agents";
import tasksRouter from "./tasks";
import dashboardRouter from "./dashboard";
import prospectsRouter from "./prospects";
import diagnosesRouter from "./diagnoses";
import proposalsRouter from "./proposals";
import approvalsRouter from "./approvals";
import invoicesRouter from "./invoices";
import subscriptionsRouter from "./subscriptions";
import revenueRouter from "./revenue";
import costsRouter from "./costs";
import auditLogsRouter from "./audit-logs";
import configRouter from "./config";
import adminRouter from "./admin";
import accountRouter from "./account";
import backlogRouter from "./backlog";
import dailySprintsRouter from "./daily-sprints";
import roadmapRouter from "./roadmap";
import bugsRouter from "./bugs";
import ideasRouter from "./ideas";
import automationsRouter from "./automations";
import sequencesRouter from "./sequences";
import prospectingAuditsRouter from "./prospecting-audits";
import smartOnboardingRouter from "./smart-onboarding";
import workflowsRouter from "./workflows";
import workflowTemplatesRouter from "./workflow-templates";
import incidentsRouter from "./incidents";
import qualityTicketsRouter from "./quality-tickets";
import contractsRouter from "./contracts";
import directorsRouter from "./directors";
import mundosRouter from "./mundos";
import organizationsRouter from "./organizations";
import clientRoomErrorsRouter from "./client-room-errors";
import clientApprovalsRouter from "./client-approvals";
import orchestrationEventsRouter from "./orchestration-events";
import orchestrationRulesRouter from "./orchestration-rules";
import integrationsRouter from "./integrations";
import executionsRouter from "./executions";
import contentCalendarRouter from "./content-calendar";
import socialCredentialsRouter from "./social-credentials";
import systemCredentialsRouter from "./system-credentials";
import catalogRouter from "./catalog";
import { requireAuth } from "../middlewares/requireAuth";
import { auditMiddleware } from "../middlewares/auditMiddleware";
import { clientRoleGate } from "../middlewares/clientRoleGate";

const router: IRouter = Router();

router.use(auditMiddleware);

router.use(healthRouter);
router.use(authRouter);
router.use(publicDigitalDiagnosisRouter);
router.use(publicFoundersRouter);
router.use(publicProposalsRouter);
router.use(publicInvoicesRouter);
router.use(publicCatalogRouter);

router.use(requireAuth);
router.use(clientRoleGate);

router.use(clientsRouter);
router.use(clientAccessRouter);
router.use(clientBrandRouter);
router.use(clientOnboardingRouter);
router.use("/clients/:clientId/timeline", clientTimelineRouter);
router.use("/clients/:clientId/notes", clientNotesRouter);
router.use(projectsRouter);
router.use(agentsRouter);
router.use(tasksRouter);
router.use(dashboardRouter);
router.use(prospectsRouter);
router.use(diagnosesRouter);
router.use(proposalsRouter);
router.use(approvalsRouter);
router.use(invoicesRouter);
router.use(subscriptionsRouter);
router.use(revenueRouter);
router.use(costsRouter);
router.use(auditLogsRouter);
router.use(configRouter);
router.use(adminRouter);
router.use(accountRouter);
router.use(backlogRouter);
router.use(dailySprintsRouter);
router.use(roadmapRouter);
router.use(bugsRouter);
router.use(ideasRouter);
router.use(automationsRouter);
router.use(sequencesRouter);
router.use(prospectingAuditsRouter);
router.use(directorsRouter);
router.use(mundosRouter);
router.use(smartOnboardingRouter);
router.use(workflowsRouter);
router.use(workflowTemplatesRouter);
router.use(incidentsRouter);
router.use(qualityTicketsRouter);
router.use(contractsRouter);
router.use(organizationsRouter);
router.use(clientRoomErrorsRouter);
router.use(clientApprovalsRouter);
router.use(orchestrationEventsRouter);
router.use(orchestrationRulesRouter);
router.use(integrationsRouter);
router.use(executionsRouter);
router.use("/clients/:clientId/content-calendar", contentCalendarRouter);
router.use("/clients/:clientId/social-credentials", socialCredentialsRouter);
router.use("/system-credentials", systemCredentialsRouter);
router.use(catalogRouter);

export default router;
