import { Router, type IRouter } from "express";
import healthRouter from "./health";
import clientsRouter from "./clients";
import clientAccessRouter from "./client-access";
import clientBrandRouter from "./client-brand";
import clientOnboardingRouter from "./client-onboarding";
import projectsRouter from "./projects";
import agentsRouter from "./agents";
import tasksRouter from "./tasks";
import dashboardRouter from "./dashboard";
import prospectsRouter from "./prospects";
import diagnosesRouter from "./diagnoses";
import proposalsRouter from "./proposals";
import approvalsRouter from "./approvals";
import invoicesRouter from "./invoices";
import subscriptionsRouter from "./subscriptions";
import revenueRouter from "./revenue";
import costsRouter from "./costs";
import auditLogsRouter from "./audit-logs";
import configRouter from "./config";

const router: IRouter = Router();

router.use(healthRouter);
router.use(clientsRouter);
router.use(clientAccessRouter);
router.use(clientBrandRouter);
router.use(clientOnboardingRouter);
router.use(projectsRouter);
router.use(agentsRouter);
router.use(tasksRouter);
router.use(dashboardRouter);
router.use(prospectsRouter);
router.use(diagnosesRouter);
router.use(proposalsRouter);
router.use(approvalsRouter);
router.use(invoicesRouter);
router.use(subscriptionsRouter);
router.use(revenueRouter);
router.use(costsRouter);
router.use(auditLogsRouter);
router.use(configRouter);

export default router;
