import { createContext, useContext, useState } from "react";

export type Lang = "es" | "en";

// Same architecture as coimagen-media-web's LanguageContext (createContext +
// localStorage-persisted useState + a translations.es/en object typed against
// itself) — copied deliberately, not reinvented, since the two apps are
// separate repos/deployments with no shared package for this. One real
// addition vs. that pattern: a `common` section, because client-room repeats
// chrome (Cancelar/Guardar/Próximamente/empty states) across many more pages
// than the marketing site does — without it, "Cancelar" would need its own
// translation in 6+ places that could drift out of sync.
const translations = {
  es: {
    common: {
      cancel: "Cancelar",
      save: "Guardar",
      saving: "Guardando...",
      loading: "Cargando...",
      comingSoon: "Próximamente",
      readOnly: "Solo lectura",
      clientRoom: "Client Room",
    },
    nav: {
      onboarding: "Onboarding",
      dashboard: "Dashboard",
      projects: "Estado del proyecto",
      contracts: "Contratos",
      invoices: "Facturas",
      approvals: "Aprobaciones",
      catalog: "Catálogo",
      autopublicador: "Autopublicador",
      workflow: "Workflow",
      documents: "Documentos",
      calendar: "Calendario",
      messages: "Mensajes",
      ai: "Asistente IA",
      profile: "Perfil",
      backToOS: "Volver a COIMAGEN OS",
      profileInOS: "Perfil en OS",
      editCompany: "Editar empresa",
      changePassword: "Cambiar contraseña",
      logout: "Cerrar sesión",
      switchTo: "English",
    },
    dashboard: {
      welcome: "Bienvenido",
      defaultDescription: "Este es tu portal privado. Aquí puedes ver el estado de tu proyecto, aprobar documentos y revisar facturas.",
      kpiPendingApprovals: "Aprobaciones pendientes",
      kpiProjectStatus: "Estado del proyecto",
      kpiNextPayment: "Próximo pago",
      kpiPendingInvoices: "Facturas pendientes",
      workflowStatus: "Estado del Workflow",
      inProduction: "En producción",
      currentStagePrefix: "Etapa actual:",
      production: "Producción",
      inProcess: "En proceso",
      contractsToSign: "Contratos por firmar",
      sign: "Firmar",
      pendingApprovalsHeading: "Aprobaciones pendientes",
      viewAll: "Ver todas",
      review: "Revisar",
      quickAccess: "Accesos rápidos",
      viewProjects: "Ver proyectos",
      myInvoices: "Mis facturas",
    },
    onboarding: {
      title: "Onboarding",
      subtitle: "Accesos e información que tu agencia necesita para arrancar",
      notStarted: "Tu agencia todavía no inició el checklist de onboarding para tu cuenta.",
      completedText: (done: number, total: number) => `${done} de ${total} completados`,
      agencyTracking: "Tu agencia va marcando cada punto conforme lo recibe",
      received: "Recibido",
      pending: "Pendiente",
      notesFromAgency: "Notas de tu agencia",
      checklist: {
        hasLogo: "Logo en alta resolución",
        hasBrandColors: "Colores y guía de marca",
        hasBusinessInfo: "Información del negocio",
        hasWebsiteAccess: "Acceso al sitio web",
        hasDomainAccess: "Acceso al dominio",
        hasHostingAccess: "Acceso al hosting",
        hasFacebookAccess: "Acceso a Facebook",
        hasInstagramAccess: "Acceso a Instagram",
        hasGoogleBusinessAccess: "Acceso a Google Business",
        hasWhatsappAccess: "Acceso a WhatsApp Business",
      },
    },
    projects: {
      title: "Proyectos",
      countLabel: (n: number) => (n === 1 ? "1 proyecto activo" : `${n} proyectos activos`),
      emptyTitle: "No hay proyectos registrados para esta organización",
      emptyHint: "Vincula un cliente en la configuración del Client Room",
      delivery: "Entrega:",
      priority: "Prioridad:",
      status: {
        planning: "Planeación",
        active: "Activo",
        in_progress: "En progreso",
        on_hold: "En pausa",
        completed: "Completado",
      } as Record<string, string>,
    },
    workflow: {
      title: "Workflow",
      subtitle: "Estado actual de tu proyecto",
      currentStageLabel: "Etapa actual: Producción",
      stageOfTotal: (current: number, total: number) => `Etapa ${current} de ${total} — En proceso`,
      completed: "Completado",
      inProgress: "En progreso",
      stages: [
        { name: "Lead", desc: "Contacto inicial y calificación del prospecto" },
        { name: "Diagnóstico", desc: "Análisis de necesidades y situación actual del cliente" },
        { name: "Propuesta", desc: "Presentación de la propuesta comercial personalizada" },
        { name: "Contrato", desc: "Firma del contrato y acuerdo de servicio" },
        { name: "Pago", desc: "Confirmación del pago inicial o total" },
        { name: "Onboarding", desc: "Bienvenida, recolección de información y accesos" },
        { name: "Producción", desc: "Ejecución del servicio contratado" },
        { name: "QA", desc: "Revisión de calidad y pruebas antes de entrega" },
        { name: "Entrega", desc: "Entrega formal del proyecto al cliente" },
        { name: "Customer Success", desc: "Seguimiento, soporte y relación a largo plazo" },
      ],
    },
    approvals: {
      title: "Aprobaciones",
      subtitle: "Documentos pendientes de revisión",
      newRequest: "Nueva solicitud",
      statPending: "Pendientes",
      statApproved: "Aprobados",
      statWithChanges: "Con cambios",
      tabAll: "Todos",
      emptyCategory: "No hay documentos en esta categoría",
      viewFile: "Ver archivo",
      commentLabel: "Comentario:",
      btnApprove: "Aprobar",
      btnChanges: "Cambios",
      btnComment: "Comentar",
      btnAddComment: "Agregar comentario",
      dialogApproveTitle: "Aprobar documento",
      dialogChangesTitle: "Solicitar cambios",
      dialogCommentTitle: "Agregar comentario",
      document: "Documento",
      observations: "Observaciones",
      commentField: "Comentario",
      approvedPlaceholder: "Aprobado, sin observaciones...",
      changesPlaceholder: "Por favor ajustar...",
      commentPlaceholder: "Escribir comentario...",
      yourName: "Tu nombre",
      reviewerNamePlaceholder: "Nombre del revisor",
      ctaApprove: "Aprobar",
      ctaChanges: "Solicitar cambios",
      ctaComment: "Enviar comentario",
      newRequestTitle: "Nueva solicitud de aprobación",
      typeLabel: "Tipo *",
      titleLabel: "Título *",
      titlePlaceholder: "Ej: Diseño landing page v2",
      descriptionLabel: "Descripción",
      fileUrlLabel: "URL del archivo",
      fileUrlPlaceholder: "https://drive.google.com/...",
      requestedByLabel: "Solicitado por",
      requestedByPlaceholder: "Nombre del equipo",
      creating: "Creando...",
      create: "Crear",
      status: {
        pending: "Pendiente",
        approved: "Aprobado",
        changes_requested: "Cambios solicitados",
      } as Record<string, string>,
      types: {
        diseño: "Diseño",
        landing: "Landing Page",
        video: "Video",
        contenido: "Contenido",
        logotipo: "Logotipo",
        material_grafico: "Material Gráfico",
        contrato: "Contrato",
        otro: "Otro",
      } as Record<string, string>,
      deleteConfirmTitle: "¿Eliminar aprobación?",
      deleteConfirmDesc: "Esta acción no se puede deshacer.",
      delete: "Eliminar",
    },
    contracts: {
      title: "Contratos",
      countLabel: (n: number) => (n === 1 ? "1 contrato" : `${n} contratos`),
      emptyMsg: "No hay contratos registrados",
      signedLabel: "Firmado:",
      expiresLabel: "Vence:",
      signing: "Firmando...",
      sign: "Firmar",
      status: {
        draft: "Borrador", sent: "Enviado", signed: "Firmado",
        active: "Activo", expired: "Vencido", cancelled: "Cancelado",
      } as Record<string, string>,
      types: {
        desarrollo_web: "Desarrollo Web", seo: "SEO", google_business: "Google Business",
        automatizacion_ia: "Automatización IA", coimagen_os: "COIMAGEN OS", medical_os: "Medical OS",
        mensualidad: "Mensualidad", nda: "NDA", addendum: "Addendum", renovacion: "Renovación",
        carta_aprobacion_visual: "Carta de Aprobación", carta_entrega_final: "Carta de Entrega",
      } as Record<string, string>,
    },
    invoices: {
      title: "Facturas",
      countLabel: (n: number) => (n === 1 ? "1 factura" : `${n} facturas`),
      totalPaid: "Total pagado",
      pendingAmount: "Por pagar",
      totalInvoices: "Total facturas",
      emptyMsg: "No hay facturas registradas",
      invoiceNumber: "Factura #",
      issuedLabel: "Emitida:",
      dueLabel: "Vence:",
      status: {
        draft: "Borrador", sent: "Enviada", paid: "Pagada",
        overdue: "Vencida", cancelled: "Cancelada",
      } as Record<string, string>,
    },
    documents: {
      title: "Documentos",
      subtitle: "Contratos, NDAs y material entregado",
      contractsAndAgreements: "Contratos y acuerdos",
      emptyMsg: "No hay documentos disponibles",
      signed: "Firmado",
      pdfComingSoon: "PDF (próximamente)",
      googleDrive: "Google Drive",
      driveDesc: "La integración con Drive estará disponible próximamente para compartir presentaciones, briefs y material entregado.",
      types: {
        nda: "NDA", addendum: "Addendum", renovacion: "Renovación",
        carta_aprobacion_visual: "Carta de Aprobación Visual", carta_entrega_final: "Carta de Entrega Final",
        desarrollo_web: "Contrato Desarrollo Web", seo: "Contrato SEO",
        google_business: "Contrato Google Business", automatizacion_ia: "Contrato Automatización IA",
        coimagen_os: "Contrato COIMAGEN OS", medical_os: "Contrato Medical OS", mensualidad: "Contrato Mensualidad",
      } as Record<string, string>,
    },
    messages: {
      title: "Mensajes",
      subtitle: "Canal de comunicación directa con tu equipo",
      underConstruction: "Canal de mensajes en construcción",
      comingSoonDesc: "Muy pronto podrás comunicarte directamente con el equipo de COIMAGEN desde tu Client Room, sin necesidad de correo externo.",
      whatsComing: "Lo que vendrá",
      features: [
        "Mensajes directos con tu equipo COIMAGEN",
        "Hilos por proyecto y tarea",
        "Notificaciones de actualizaciones",
        "Historial completo de conversaciones",
        "Adjuntar archivos y referencias",
        "Menciones con @nombre",
      ],
      needNow: "¿Necesitas comunicarte ahora?",
      contactHint: "Escríbenos a hola@coimagenmedia.com o a tu Director asignado",
    },
    ai: {
      title: "Asistente IA",
      subtitle: "Tu asistente privado de COIMAGEN OS",
      underConstruction: "Asistente IA en construcción",
      comingSoonDesc: "Tu asistente personal conocerá únicamente la información de tu organización. Podrá responder preguntas, generar resúmenes y ayudarte a entender el avance de tu proyecto.",
      plannedCapabilities: "Capacidades planificadas",
      capabilities: [
        "Consultar el estado de tu proyecto en tiempo real",
        "Revisar contratos y facturas con lenguaje natural",
        "Obtener resúmenes de avance del workflow",
        "Información 100% privada — solo de tu organización",
      ],
      securityGuaranteed: "🔒 Seguridad garantizada",
      securityDesc: "El asistente IA solo tendrá acceso a la información de tu organización. Nunca podrá consultar datos de otros clientes.",
    },
    autopublicador: {
      title: "Autopublicador Social",
      subtitle: "Borradores generados para tus redes — apruébalos para publicarlos",
      pendingCount: (n: number) => (n === 1 ? "1 pendiente" : `${n} pendientes`),
      emptyMsg: "Todavía no hay borradores de contenido para tu cuenta.",
      approveAndPublish: "Aprobar y publicar",
      approvedToast: "Aprobado",
      publishedToast: "Publicado",
      approveErrorToast: "No se pudo aprobar",
      status: {
        draft: "Borrador",
        pending_approval: "Pendiente de tu aprobación",
        approved: "Aprobado",
        published: "Publicado",
        failed: "Falló al publicar",
      } as Record<string, string>,
      statusColor: {
        draft: "bg-muted text-muted-foreground border-border",
        pending_approval: "bg-amber-400/15 text-amber-400 border-amber-400/30",
        approved: "bg-emerald-400/15 text-emerald-400 border-emerald-400/30",
        published: "bg-violet-400/15 text-violet-400 border-violet-400/30",
        failed: "bg-red-400/15 text-red-400 border-red-400/30",
      } as Record<string, string>,
      networks: {
        meta_facebook: "Facebook",
        meta_instagram: "Instagram",
        linkedin: "LinkedIn",
      } as Record<string, string>,
    },
    profile: {
      editDialogTitle: "Editar perfil de organización",
      nameLabel: "Nombre",
      descLabel: "Descripción",
      emailLabel: "Email de contacto",
      phoneLabel: "Teléfono",
      colorLabel: "Color de marca",
      title: "Perfil",
      subtitle: "Información de tu organización",
      edit: "Editar",
      active: "Activo",
      clientRoomUrl: "Client Room URL",
      orgId: "ID Organización",
      contactEmail: "Email de contacto",
      phone: "Teléfono",
      portalSecurity: "Seguridad del portal",
      portalSecurityDesc: "Tu Client Room está aislado. Solo puedes ver información de tu organización. El acceso es controlado por el equipo de COIMAGEN.",
      createdLabel: "Creado:",
    },
  },
  en: {
    common: {
      cancel: "Cancel",
      save: "Save",
      saving: "Saving...",
      loading: "Loading...",
      comingSoon: "Coming soon",
      readOnly: "Read-only",
      clientRoom: "Client Room",
    },
    nav: {
      onboarding: "Onboarding",
      dashboard: "Dashboard",
      projects: "Project status",
      contracts: "Contracts",
      invoices: "Invoices",
      approvals: "Approvals",
      catalog: "Catalog",
      autopublicador: "Autopublisher",
      workflow: "Workflow",
      documents: "Documents",
      calendar: "Calendar",
      messages: "Messages",
      ai: "AI Assistant",
      profile: "Profile",
      backToOS: "Back to COIMAGEN OS",
      profileInOS: "Profile in OS",
      editCompany: "Edit company",
      changePassword: "Change password",
      logout: "Log out",
      switchTo: "Español",
    },
    dashboard: {
      welcome: "Welcome",
      defaultDescription: "This is your private portal. Here you can see your project status, approve documents, and review invoices.",
      kpiPendingApprovals: "Pending approvals",
      kpiProjectStatus: "Project status",
      kpiNextPayment: "Next payment",
      kpiPendingInvoices: "Pending invoices",
      workflowStatus: "Workflow status",
      inProduction: "In production",
      currentStagePrefix: "Current stage:",
      production: "Production",
      inProcess: "In progress",
      contractsToSign: "Contracts to sign",
      sign: "Sign",
      pendingApprovalsHeading: "Pending approvals",
      viewAll: "View all",
      review: "Review",
      quickAccess: "Quick access",
      viewProjects: "View projects",
      myInvoices: "My invoices",
    },
    onboarding: {
      title: "Onboarding",
      subtitle: "Access and information your agency needs to get started",
      notStarted: "Your agency hasn't started the onboarding checklist for your account yet.",
      completedText: (done: number, total: number) => `${done} of ${total} completed`,
      agencyTracking: "Your agency marks each item as it's received",
      received: "Received",
      pending: "Pending",
      notesFromAgency: "Notes from your agency",
      checklist: {
        hasLogo: "High-resolution logo",
        hasBrandColors: "Brand colors and guide",
        hasBusinessInfo: "Business information",
        hasWebsiteAccess: "Website access",
        hasDomainAccess: "Domain access",
        hasHostingAccess: "Hosting access",
        hasFacebookAccess: "Facebook access",
        hasInstagramAccess: "Instagram access",
        hasGoogleBusinessAccess: "Google Business access",
        hasWhatsappAccess: "WhatsApp Business access",
      },
    },
    projects: {
      title: "Projects",
      countLabel: (n: number) => (n === 1 ? "1 active project" : `${n} active projects`),
      emptyTitle: "No projects registered for this organization",
      emptyHint: "Link a client in the Client Room settings",
      delivery: "Due:",
      priority: "Priority:",
      status: {
        planning: "Planning",
        active: "Active",
        in_progress: "In progress",
        on_hold: "On hold",
        completed: "Completed",
      } as Record<string, string>,
    },
    workflow: {
      title: "Workflow",
      subtitle: "Your project's current status",
      currentStageLabel: "Current stage: Production",
      stageOfTotal: (current: number, total: number) => `Stage ${current} of ${total} — In progress`,
      completed: "Completed",
      inProgress: "In progress",
      stages: [
        { name: "Lead", desc: "Initial contact and prospect qualification" },
        { name: "Diagnosis", desc: "Analysis of the client's needs and current situation" },
        { name: "Proposal", desc: "Presentation of the tailored commercial proposal" },
        { name: "Contract", desc: "Contract signing and service agreement" },
        { name: "Payment", desc: "Confirmation of the initial or full payment" },
        { name: "Onboarding", desc: "Welcome, information gathering, and access collection" },
        { name: "Production", desc: "Execution of the contracted service" },
        { name: "QA", desc: "Quality review and testing before delivery" },
        { name: "Delivery", desc: "Formal delivery of the project to the client" },
        { name: "Customer Success", desc: "Long-term follow-up, support, and relationship" },
      ],
    },
    approvals: {
      title: "Approvals",
      subtitle: "Documents pending review",
      newRequest: "New request",
      statPending: "Pending",
      statApproved: "Approved",
      statWithChanges: "With changes",
      tabAll: "All",
      emptyCategory: "No documents in this category",
      viewFile: "View file",
      commentLabel: "Comment:",
      btnApprove: "Approve",
      btnChanges: "Changes",
      btnComment: "Comment",
      btnAddComment: "Add comment",
      dialogApproveTitle: "Approve document",
      dialogChangesTitle: "Request changes",
      dialogCommentTitle: "Add comment",
      document: "Document",
      observations: "Observations",
      commentField: "Comment",
      approvedPlaceholder: "Approved, no observations...",
      changesPlaceholder: "Please adjust...",
      commentPlaceholder: "Write a comment...",
      yourName: "Your name",
      reviewerNamePlaceholder: "Reviewer's name",
      ctaApprove: "Approve",
      ctaChanges: "Request changes",
      ctaComment: "Send comment",
      newRequestTitle: "New approval request",
      typeLabel: "Type *",
      titleLabel: "Title *",
      titlePlaceholder: "E.g.: Landing page design v2",
      descriptionLabel: "Description",
      fileUrlLabel: "File URL",
      fileUrlPlaceholder: "https://drive.google.com/...",
      requestedByLabel: "Requested by",
      requestedByPlaceholder: "Team member's name",
      creating: "Creating...",
      create: "Create",
      status: {
        pending: "Pending",
        approved: "Approved",
        changes_requested: "Changes requested",
      } as Record<string, string>,
      types: {
        diseño: "Design",
        landing: "Landing Page",
        video: "Video",
        contenido: "Content",
        logotipo: "Logo",
        material_grafico: "Graphic Material",
        contrato: "Contract",
        otro: "Other",
      } as Record<string, string>,
      deleteConfirmTitle: "Delete approval?",
      deleteConfirmDesc: "This action cannot be undone.",
      delete: "Delete",
    },
    contracts: {
      title: "Contracts",
      countLabel: (n: number) => (n === 1 ? "1 contract" : `${n} contracts`),
      emptyMsg: "No contracts registered",
      signedLabel: "Signed:",
      expiresLabel: "Expires:",
      signing: "Signing...",
      sign: "Sign",
      status: {
        draft: "Draft", sent: "Sent", signed: "Signed",
        active: "Active", expired: "Expired", cancelled: "Cancelled",
      } as Record<string, string>,
      types: {
        desarrollo_web: "Web Development", seo: "SEO", google_business: "Google Business",
        automatizacion_ia: "AI Automation", coimagen_os: "COIMAGEN OS", medical_os: "Medical OS",
        mensualidad: "Monthly Plan", nda: "NDA", addendum: "Addendum", renovacion: "Renewal",
        carta_aprobacion_visual: "Approval Letter", carta_entrega_final: "Delivery Letter",
      } as Record<string, string>,
    },
    invoices: {
      title: "Invoices",
      countLabel: (n: number) => (n === 1 ? "1 invoice" : `${n} invoices`),
      totalPaid: "Total paid",
      pendingAmount: "Pending",
      totalInvoices: "Total invoices",
      emptyMsg: "No invoices registered",
      invoiceNumber: "Invoice #",
      issuedLabel: "Issued:",
      dueLabel: "Due:",
      status: {
        draft: "Draft", sent: "Sent", paid: "Paid",
        overdue: "Overdue", cancelled: "Cancelled",
      } as Record<string, string>,
    },
    documents: {
      title: "Documents",
      subtitle: "Contracts, NDAs, and delivered material",
      contractsAndAgreements: "Contracts and agreements",
      emptyMsg: "No documents available",
      signed: "Signed",
      pdfComingSoon: "PDF (coming soon)",
      googleDrive: "Google Drive",
      driveDesc: "Drive integration will soon be available for sharing presentations, briefs, and delivered material.",
      types: {
        nda: "NDA", addendum: "Addendum", renovacion: "Renewal",
        carta_aprobacion_visual: "Visual Approval Letter", carta_entrega_final: "Final Delivery Letter",
        desarrollo_web: "Web Development Contract", seo: "SEO Contract",
        google_business: "Google Business Contract", automatizacion_ia: "AI Automation Contract",
        coimagen_os: "COIMAGEN OS Contract", medical_os: "Medical OS Contract", mensualidad: "Monthly Plan Contract",
      } as Record<string, string>,
    },
    messages: {
      title: "Messages",
      subtitle: "Direct communication channel with your team",
      underConstruction: "Messaging channel under construction",
      comingSoonDesc: "Soon you'll be able to communicate directly with the COIMAGEN team from your Client Room, no external email needed.",
      whatsComing: "What's coming",
      features: [
        "Direct messages with your COIMAGEN team",
        "Threads by project and task",
        "Update notifications",
        "Complete conversation history",
        "Attach files and references",
        "@name mentions",
      ],
      needNow: "Need to reach us now?",
      contactHint: "Write to us at hola@coimagenmedia.com or your assigned Director",
    },
    ai: {
      title: "AI Assistant",
      subtitle: "Your private COIMAGEN OS assistant",
      underConstruction: "AI Assistant under construction",
      comingSoonDesc: "Your personal assistant will only know your organization's information. It'll be able to answer questions, generate summaries, and help you understand your project's progress.",
      plannedCapabilities: "Planned capabilities",
      capabilities: [
        "Check your project's status in real time",
        "Review contracts and invoices in natural language",
        "Get workflow progress summaries",
        "100% private information — only your organization's",
      ],
      securityGuaranteed: "🔒 Guaranteed security",
      securityDesc: "The AI assistant will only ever access your organization's information. It can never query other clients' data.",
    },
    autopublicador: {
      title: "Social Autopublisher",
      subtitle: "Drafts generated for your social channels — approve them to publish",
      pendingCount: (n: number) => (n === 1 ? "1 pending" : `${n} pending`),
      emptyMsg: "No content drafts for your account yet.",
      approveAndPublish: "Approve and publish",
      approvedToast: "Approved",
      publishedToast: "Published",
      approveErrorToast: "Couldn't approve",
      status: {
        draft: "Draft",
        pending_approval: "Pending your approval",
        approved: "Approved",
        published: "Published",
        failed: "Failed to publish",
      } as Record<string, string>,
      statusColor: {
        draft: "bg-muted text-muted-foreground border-border",
        pending_approval: "bg-amber-400/15 text-amber-400 border-amber-400/30",
        approved: "bg-emerald-400/15 text-emerald-400 border-emerald-400/30",
        published: "bg-violet-400/15 text-violet-400 border-violet-400/30",
        failed: "bg-red-400/15 text-red-400 border-red-400/30",
      } as Record<string, string>,
      networks: {
        meta_facebook: "Facebook",
        meta_instagram: "Instagram",
        linkedin: "LinkedIn",
      } as Record<string, string>,
    },
    profile: {
      editDialogTitle: "Edit organization profile",
      nameLabel: "Name",
      descLabel: "Description",
      emailLabel: "Contact email",
      phoneLabel: "Phone",
      colorLabel: "Brand color",
      title: "Profile",
      subtitle: "Your organization's information",
      edit: "Edit",
      active: "Active",
      clientRoomUrl: "Client Room URL",
      orgId: "Organization ID",
      contactEmail: "Contact email",
      phone: "Phone",
      portalSecurity: "Portal security",
      portalSecurityDesc: "Your Client Room is isolated. You can only see your organization's information. Access is controlled by the COIMAGEN team.",
      createdLabel: "Created:",
    },
  },
};

type Translations = typeof translations.es;

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const LANG_STORAGE_KEY = "coimagen-lang";

function getStoredLang(): Lang {
  try {
    const stored = localStorage.getItem(LANG_STORAGE_KEY);
    if (stored === "es" || stored === "en") return stored;
  } catch {
    // localStorage unavailable (e.g. private browsing) — fall back to default
  }
  return "es";
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(getStoredLang);

  const setLang = (l: Lang) => {
    setLangState(l);
    try {
      localStorage.setItem(LANG_STORAGE_KEY, l);
    } catch {
      // localStorage unavailable — selection just won't persist
    }
  };

  const t = translations[lang] as Translations;
  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}
