import { pgTable, serial, integer, text, timestamp } from "drizzle-orm/pg-core";
import { invoicesTable } from "./invoices";

// The REAL SAT-compliant fiscal invoice (CFDI) PDF, generated by Camila's
// accountant outside this system once she forwards them the notification
// email (see lib/fiscal-data/email.ts) and uploaded here by staff — separate
// from invoice_fiscal_data/client_fiscal_data (the client's RFC/constancia
// submitted BEFORE paying, used only to build that notification). Applies
// to any invoices row that required a fiscal invoice — one-time cuotas
// (CASO 1) and the auto-created monthly-charge invoices (CASO 2,
// webhooks-paypal.ts's handleRecurringPaymentCompleted) alike, since both
// are ordinary rows in the same invoices table. Uploading triggers an
// automatic email to the client with the PDF attached.
export const invoiceFiscalDocumentsTable = pgTable("invoice_fiscal_documents", {
  id: serial("id").primaryKey(),
  invoiceId: integer("invoice_id").notNull().references(() => invoicesTable.id, { onDelete: "cascade" }),
  fileKey: text("file_key").notNull(),
  fileName: text("file_name").notNull(),
  uploadedByEmail: text("uploaded_by_email"),
  uploadedAt: timestamp("uploaded_at").notNull().defaultNow(),
  emailedToClientAt: timestamp("emailed_to_client_at"),
});

export type InvoiceFiscalDocument = typeof invoiceFiscalDocumentsTable.$inferSelect;
export type InvoiceFiscalDocumentInsert = typeof invoiceFiscalDocumentsTable.$inferInsert;
